---
title: "Untitled"
output: html_document
date: '2022-02-18'
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(sf)

theme_set(theme_minimal())
```

```{r}
ak_regions <- st_read("~/Downloads/shapefile_demo_data/ak_regions_simp.shp")
ak_rivers <- st_read("~/Downloads/shapefile_demo_data/ak_rivers_simp.shp")

populations <- read_csv("~/Downloads/shapefile_demo_data/alaska_population.csv") %>% 
  rename(longitude = lng, latitude = lat) %>% 
  st_as_sf(coords = c("longitude", "latitude"), crs = 4326)

# crsuggest::suggest_crs(ak_regions)

my_crs <- 6393

ak_regions <- ak_regions %>% 
  st_transform(crs = my_crs)

populations <- populations %>% 
  st_transform(crs = my_crs) %>% 
  st_join(ak_regions, join = st_within) %>% 
  group_by(region) %>% 
  summarise(total_population = sum(population))

ak_regions <- ak_regions %>% 
  mutate(area = st_area(geometry)) %>%
  mutate(area = units::set_units(area, km^2)) %>%
  mutate(area = as.numeric(area))

ak_rivers <- ak_rivers %>% 
  st_transform(crs = my_crs)

ggplot() +
  geom_sf(data = ak_regions, aes(fill = area), size = 0.1) +
  geom_sf(data = ak_rivers, size = 0.1, color = "blue") +
  geom_sf(
    data = populations,
    aes(size = total_population),
    color = "#3c3c3c"
  ) +
  scale_x_continuous(breaks = seq(-180, 180, by = 10)) +
  scale_size(
    labels = scales::label_number_si(),
    range = c(0.1, 2)
  ) +
  rcartocolor::scale_fill_carto_c(
    labels = scales::label_number(),
    palette = 5,
  ) +
  labs(
    size = "Total population",
    fill = ""
  )
```

